### ISSUE TITLE
[NPC][Mulgore] Deviate Viper

### ISSUE THREAD

**Issue by Take1hat** [Take1hat/Bug-tracker-for-WOD#69] opened 2022-07-18 17:53 UTC
## What is the Bug? (Brief Overview)
Random dungeon Elite in the overworld.
## WoW Head Link to Quest, Item etc.
NPC: https://www.wowhead.com/npc=5755/deviate-viper

## Expected Behavior
No snek.

## Current Behavior
Surprise snek.

## Steps to Reproduce

1. Go to location.
2. Get slaughtered (if you're a lowbie)
3.
4.

## Attach a Video Link or Screenshot
PIC: https://gyazo.com/9fcd4dba7d3169f61b311d07b6418c2d

**Comment by Alleujah** [comment] 2022-08-03 01:40
Unable to reproduce. Mob is not in this area. Please close this.

**Comment by Alleujah** [comment] 2022-08-03 01:48
Unable to reproduce. The mob is not in this area. Please close this.

**Closed as not planned** 2022-08-03 01:48 UTC
